[workspace]

[package]
name = "vk_mem_test"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = { git = "https://github.com/ash-rs/ash", rev = "f4c2ca3e4f6b998d5254ad101a32f024d87cdec2", default-features = false, features = ["linked", "debug", "std", "provisional"] }
vk-mem = { path = "../vendor/vk-mem" }

[profile.dev.package."*"]
opt-level = 3
